kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"  # set to true to process this configMap. For staging set to false.
data:
  template: |
    {
        "declaration": {
            "k8s": {
                "Shared": {
                    "ingress_10_192_75_108_80": {
                        "profileTrafficLog": {
                            "bigip": "/Common/Shared/telemetry_traffic_log_profile"
                        },
                        "persistenceMethods": [],
                        "serviceDownImmediateAction": "drop"
                    }
                }
            }
        }
    }