apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: k8s-bigip-ctlr
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      annotations: 
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
        seccomp.security.alpha.kubernetes.io/pod: unconfined
      creationTimestamp: ~
      labels: 
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec: 
      containers: 
        - 
          args: 
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=192.168.200.92"
            - "--bigip-partition=k8s"
            - "--namespace=cistest100"
            - "--namespace=cistest101"
            - "--namespace=cistest103"
            - "--namespace=cistest104"
            - "--namespace=cistest105"
            - "--namespace=cistest106"
            - "--namespace=cistest107"
            - "--namespace=cistest108"
            - "--namespace=cistest109"
            - "--namespace=cistest110"
            - "--namespace=cistest111"
            - "--namespace=cistest112"
            - "--namespace=cistest113"
            - "--namespace=cistest114"
            - "--namespace=cistest115"
            - "--namespace=cistest116"
            - "--namespace=cistest117"
            - "--namespace=cistest118"
            - "--namespace=cistest119"
            - "--namespace=cistest120"
            - "--namespace=cistest121"
            - "--namespace=cistest122"
            - "--namespace=cistest123"
            - "--namespace=cistest124"
            - "--namespace=cistest125"
            - "--namespace=cistest126"
            - "--namespace=cistest127"
            - "--namespace=cistest128"
            - "--namespace=cistest129"
            - "--namespace=cistest130"
            - "--namespace=cistest131"
            - "--namespace=cistest132"
            - "--namespace=cistest133"
            - "--namespace=cistest134"
            - "--namespace=cistest135"
            - "--namespace=cistest136"
            - "--namespace=cistest137"
            - "--namespace=cistest138"
            - "--namespace=cistest139"
            - "--namespace=cistest140"
            - "--namespace=cistest141"
            - "--namespace=cistest142"
            - "--namespace=cistest143"
            - "--namespace=cistest144"
            - "--namespace=cistest145"
            - "--namespace=cistest146"
            - "--namespace=cistest147"
            - "--namespace=cistest148"
            - "--namespace=cistest149"
            - "--namespace=cistest150"
            - "--namespace=cistest151"
            - "--namespace=cistest152"
            - "--namespace=cistest153"
            - "--namespace=cistest154"
            - "--namespace=cistest155"
            - "--namespace=cistest156"
            - "--namespace=cistest157"
            - "--namespace=cistest158"
            - "--namespace=cistest159"
            - "--namespace=cistest160"
            - "--pool-member-type=cluster"
            - "--flannel-name=fl-vxlan"
            - "--log-level=DEBUG"
            - "--insecure=true"
            - "--log-as3-response=true"
          command: 
            - /app/bin/k8s-bigip-ctlr
          env: 
            - 
              name: BIGIP_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: bigip-login
            - 
              name: BIGIP_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: bigip-login
          image: "f5networks/k8s-bigip-ctlr:2.1.1"
          name: f5-server
      serviceAccountName: k8s-bigip-ctlr